// Expected: 'success'
let (x = "error")
try {
  x := "success";
  throw "err"
} catch { func (e) {
  x
}}
