// Expected: 'success'
try {
    throw "error"
} catch {
    func(e) { "success" }
}
