// Expected: 'success'
let (x = 1)
try {
  try {
    throw "success"
  } finally {
    "failure"
  }
} catch { func (e) {
  e
}}
